name: 'Continuous Delivery'

on:
  push:
    branches:
      - main
  workflow_dispatch:  # For manual execution while testing cicd

env:
  AWS_REGION: us-east-1
  ECR_REPO_ID: 620593188645
  ECS_CLUSTER_NAME: PredictionCluster
  ECS_SERVICE_NAME: prediction-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    # needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build --target main -t prediction-app:latest .
          docker tag prediction-app:latest ${{ env.ECR_REPO_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/prediction-app:latest

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPO_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Push Docker image to ECR
        run: docker push ${{ env.ECR_REPO_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/prediction-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.ECS_SERVICE_NAME }} --force-new-deployment
